UPDATE creature_ai_texts SET content_default='There is no escape for you. The Crusade shall destroy all who carry the scourge''s taint.' WHERE entry=-1307;
UPDATE creature_ai_texts SET content_default='You carry the taint of the scourge. Prepare to enter the twisting nether.' WHERE entry=-1306;
UPDATE creature_ai_texts SET content_default='The light condemns all who harbor evil. Now you will die!' WHERE entry=-1305;
UPDATE creature_ai_texts SET content_default='%s''s death cry has stirred the nearby silithid hive.' WHERE entry=-1147;
UPDATE creature_ai_texts SET content_default='You carry the taint of the scourge. Prepare to enter the twisting nether.' WHERE entry=-1029;
UPDATE creature_ai_texts SET content_default='The %s doen''t look like it minds the crystal''s effect.' WHERE entry=-909;
UPDATE creature_ai_texts SET content_default='For Kargath! For Victory!' WHERE entry=-674;
UPDATE creature_ai_texts SET content_default='Stand firm, brothers. And don''t worry! Size is on our side!' WHERE entry=-529;
UPDATE creature_ai_texts SET content_default='The Council of Duskwood must take action. Evil lingers in the air.' WHERE entry=-462;
UPDATE creature_ai_texts SET content_default='Wait...you are not my husband. But he must have sent you. And you...look..delicious!' WHERE entry=-460;
UPDATE creature_ai_texts SET content_default='Undead are crawling all over the land. Where is the Stormwind Army?' WHERE entry=-459;
UPDATE creature_ai_texts SET content_default='The people of Darkshire expect more from the Council. We cannot let them suffer from this unholy wrath which plagues us.' WHERE entry=-458;
UPDATE creature_ai_texts SET content_default='Constant bickering will get us nowhere. We need to take action.' WHERE entry=-454;
UPDATE creature_ai_texts SET content_default='%s''s death cry has stirred the nearby silithid hive.' WHERE entry=-345;
UPDATE creature_ai_texts SET content_default='%s''s death cry has stirred the nearby silithid hive.' WHERE entry=-344;
UPDATE creature_ai_texts SET content_default='The troggs...they never stop coming. Die trogg! Die!' WHERE entry=-191;
UPDATE creature_ai_texts SET content_default='This sickness clouds my vision, but I know you must be a trogg. Die foul invader!' WHERE entry=-189;
UPDATE creature_ai_texts SET content_default='A foul trogg if ever I saw one. Die!' WHERE entry=-188;
UPDATE creature_ai_texts SET content_default='What good does this violence serve? What is done is done. I have failed my people.' WHERE entry=-116;
UPDATE creature_ai_texts SET content_default='I cannot stand the pain. I must find a new source.' WHERE entry=-114;